version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=null
      - MYSQL_DATABASE=eventsProject
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  kaddem-backend:
    depends_on:
      - mysqldb
    image: rania/eventsproject:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
    "spring.datasource.url": "jdbc:mysql://mysqldb:3306/eventsProject?createDatabaseIfNotExist=true",
    "spring.datasource.username": "root",
    "spring.datasource.password": null,
    "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect",
    "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db: